config/routes.rb
Ghoulpool::Application.routes.draw do

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout"  }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  root :to => "pages#home"
  
  match "dashboard" => 'dashboard#index', :via => :get
  
  resources :ghouls, :only => [:show]
  resources :pools, :except => [:index] do
    resources :entries, :except => [:edit, :update]
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :manage, Ghoul
      can [:read, :create], Pool
      can [:update, :destroy], Pool, :user_id => user.id
      can :manage, Entry, :user_id => user.id
      can :manage, Rule do |rule|
        rule.pool.owner = user
      end
    end
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :ghoul_attributes
  validate :ghoul_must_be_living, :on => :create
  validate :ghoul_must_unique_for_owner_and_pool, :on => :create
  belongs_to :owner, :class_name => "User", :foreign_key => :user_id
  belongs_to :ghoul
  belongs_to :pool
  has_one :rule, :through => :pool
  accepts_nested_attributes_for :ghoul
  
  def value
    return 0 if ghoul.died_on.blank?
    days_alive = ghoul.died_on - ghoul.born_on
    return days_alive if rule.blank?
    function = rule.function.gsub(':days_alive', days_alive.to_s)
    instance_eval(function)
  end
  
  def ghoul_must_be_living
    errors.add(:ghoul, "must be alive") unless ghoul.alive?
  end
  
  def ghoul_must_unique_for_owner_and_pool
    return if ghoul.id.blank?
    pool.user_entries(owner).each do |entry|
      if entry.ghoul.id == ghoul.id
        errors.add(:ghoul, "already chosen")
        break
      end
    end
  end
end

app/models/ghoul.rb
class Ghoul < ActiveRecord::Base
  attr_accessible :freebase_id
  validates_presence_of :freebase_id, :name, :born_on
  validates_uniqueness_of :freebase_id, :name
  has_many :entries
  
  scope :living, where(:died_on => nil)
  scope :recent, lambda { |date| where("died_on > ?", date) }
  
  def alive?
    return @alive if defined?(@alive)
    if self.died_on.blank?
      args = { "type" => "/people/deceased_person", "id" => "#{self.freebase_id}" }
      matches = Ghoul.query_freebase(args)
      @alive = matches.blank?
    else
      @alive = false
    end
    @alive
  end
  
  def sync
    args = { 
      "type" => "/people/person", 
      "id" => self.freebase_id,
      "date_of_birth" => nil, 
      "name" => nil,
      "/people/deceased_person/date_of_death" => nil
    }
    matches = Ghoul.query_freebase(args)
    match_found = false
    unless matches.blank?
      match_found = true
      match = matches[0] # assume first hit
      self.name = match["name"]
      self.born_on = match["date_of_birth"]
      self.died_on = match["/people/deceased_person/date_of_death"]
    end
    match_found
  end
  
  def self.search(name)
    args = { 
      "type" => "/people/person", 
      "name" => "#{name}", 
      "id" => nil, 
      "date_of_birth" => nil,
      "/people/deceased_person/date_of_death" => nil 
    }
    matches = Ghoul.query_freebase(args)
    ghouls = []
    matches.each do |match|
      ghoul = Ghoul.new
      ghoul.freebase_id = match["id"]
      ghoul.name = match["name"]
      ghoul.born_on = match["date_of_birth"]
      ghoul.died_on = match["/people/deceased_person/date_of_death"]
      ghouls << ghoul
    end
    ghouls
  end
  
  def deliver_change_notifications
    users = Hash.new
    self.entries.includes(:owner).each do |entry|
      users[entry.owner.id] = entry.owner
    end
    users.each_value do |user|
      UserMailer.deliver_ghoul_change_notification(user)
    end
  end
  
  private
  
  def self.query_freebase(args)
    Ken.session.mqlread([args])
  end
end

app/models/pool.rb
class Pool < ActiveRecord::Base
  attr_accessible :name, :picks, :rule_attributes
  validates_presence_of :name, :picks
  validates_numericality_of :picks, :greater_than => 0
  has_many :entries, :dependent => :destroy
  has_many :rankings, :order => "score DESC", :dependent => :destroy
  has_one :rule, :dependent => :destroy
  belongs_to :owner, :class_name => "User", :foreign_key => :user_id
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :rule, :reject_if => lambda { |rule| rule[:function].blank? }
  before_create :add_owner_as_member
  
  def points(user=nil)
    user ||= owner
    score = 0
    user_entries = self.user_entries(user)
    user_entries.each { |entry| score += entry.value }
    score
  end
  
  def place(user=nil)
    user ||= owner
    rank = 0
    user_rankings = self.rankings(user)
    user_rankings.each do |ranking|
      rank += 1
      if ranking.user_id == user.id
        break
      end
    end
    rank
  end
  
  def user_entries(user)
    Entry.where(:user_id => user).where(:pool_id => self)
  end
  
  private
  
  def add_owner_as_member
    users << owner
  end
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  belongs_to :pool
  belongs_to :user
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  validates_presence_of :function
  belongs_to :pool
  has_one :entry, :through => :pool
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :entries
  has_many :rankings
  has_and_belongs_to_many :pools
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  protect_from_forgery
  
  # responders gem
  self.responder = ApplicationResponder
  respond_to :html
  
  def after_sign_in_path_for(resource)
    dashboard_url
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @pools = current_user.pools
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  load_and_authorize_resource :pool
  load_and_authorize_resource :entry, :through => :pool
  
  def index
    @entries = @pool.entries.page(params[:page]).per(10)
    respond_with(@entries)
  end
  
  def new
    @entry.build_ghoul
    @ghouls = []
    unless params[:search].blank?
      @ghouls = Ghoul.search(params[:search][:name])
    end
    respond_with(@entry)
  end
  
  def create
    @entry.owner = current_user
    existing_ghoul = Ghoul.where(:freebase_id => @entry.ghoul.freebase_id).first
    if existing_ghoul.blank?
      @entry.ghoul.sync
    else
      @entry.ghoul = existing_ghoul
    end
    unless @entry.save
      @ghouls = []
    end
    respond_with(@entry, :location => pool_entries_url(@pool))
  end
  
  def destroy
    @entry.destroy
    respond_with(@entry, :location => pool_entries_url(@pool))
  end
end

app/controllers/ghouls_controller.rb
class GhoulsController < ApplicationController
  load_and_authorize_resource
  
  def show
    respond_with(@ghoul)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  load_and_authorize_resource
  
  def show
    respond_with(@pool)
  end
  
  def new
    @pool.build_rule
    respond_with(@pool)
  end
  
  def create
    @pool.owner = current_user
    @pool.save
    respond_with(@pool)
  end
  
  def edit
    respond_with(@pool)
  end
  
  def update
    @pool.update_attributes(params[:pool])
    respond_with(@pool)
  end
  
  def destroy
    @pool.destroy
    respond_with(@pool, :location => dashboard_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
  def freebase_url(freebase_id)
    "http://www.freebase.com/view#{freebase_id}"
  end
  
  def freebase_metadata(ghoul)
    metadata = ghoul.name
    if ghoul.born_on.blank?
      metadata += " (birth date unknown)"
    else
      metadata += " (born #{ghoul.born_on.strftime('%m/%d/%Y')})"
    end
    metadata
  end
end

app/helpers/ghouls_helper.rb
module GhoulsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/dashboard/_pool.html.haml
%ul.pool
  %li
    %strong Name:
    = link_to pool.name, pool
  %li
    %strong Standings:
    = "#{pool.place} out of #{pool.users.count} players with a score of #{pool.points(current_user)}"
  %li
    %strong Actions:
    = link_to 'View Your Entries', pool_entries_path(pool), :class => "small-button"
    = link_to 'Update Pool', edit_pool_path(pool), :class => "small-button" if can? :update, pool
    = link_to 'Delete Pool', pool, :confirm => "Are you sure want to delete this pool?", :method => :delete, :class => "small-button" if can? :destroy, pool

app/views/dashboard/index.html.haml
.span-18.last
  %h2 Dashboard
  %hr
  .span-9
    %h3 Pools 
    .pools
      = render :partial => "pool", :collection => @pools
  .span-9.last
    Not enough, ahem, activity? Go ahead and
    = link_to 'start another pool', new_pool_path, :class => "small-button"
    %br
    %br
    %h3 Activity
    .activities

app/views/entries/_entry.html.haml
%ul
  %li
    %strong Name:
    = link_to entry.ghoul.name, entry.ghoul
  %li
    %strong Action(s):
    = link_to "Details", entry.ghoul, :class => "small-button"
    = link_to "Freebase Entry", freebase_url(entry.ghoul.freebase_id), :class => "small-button", :target => "_blank"
    = link_to "Delete", pool_entry_path(@pool, entry), :confirm => "Are you sure want to delete this ghoul?", :method => :delete, :class => "small-button" if can? :destroy, entry

app/views/entries/_form.html.haml
= render "shared/error_messages", :target => @entry
= simple_form_for :search, :url => new_pool_entry_path(@pool), :html => {:method => :get} do |f|
  = f.input :name
  = f.submit 'Find Ghouls', :class => "big-button"

app/views/entries/_ghoul.html.haml
.ghoul
  = simple_form_for [@pool, @entry] do |f|
    = f.simple_fields_for :ghoul do |g|
      = g.hidden_field :freebase_id, :value => ghoul.freebase_id
    = f.button :submit, "Add", :class => "small-form-button"
    = link_to freebase_metadata(ghoul), freebase_url(ghoul.freebase_id), :target => "_blank", :class => "name"

app/views/entries/index.html.haml
.span-18.last
  %h2= "#{@pool.name} Entries"
  %hr
  .span-9
    %h3 Ghouls
    .entries
      = render :partial => "entry", :collection => @entries
    = paginate @entries
  .span9-last
    %h3 Actions
    %ul
      %li
        = link_to "View Pool", @pool, :class => "small-button"
        - if @entries.count < @pool.picks
        = link_to 'Add Ghouls', new_pool_entry_path(@pool), :class => "small-button"

app/views/entries/new.html.haml
.span-18.last
  %h2 Add Ghouls
  %hr
  .span-9
    = render :partial => "form"
  .span-9.last
    - unless @ghouls.empty?
      %p The following matches were found. To confirm the match is correct, please view the "ghoul to be" by clicking on their name before adding them to your pool.
      .ghouls
        = render :partial => "ghoul", :collection => @ghouls, :locals => { :pool => @pool }

app/views/ghouls/show.html.haml
.span-18.last
  %h2= @ghoul.name
  %hr
.span-18.last
  %h3 Details
.span-18.last
  %h3 Statistics

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield(:title) || "Ghoulpool"
    = stylesheet_link_tag "screen", "base", "http://fonts.googleapis.com/css?family=Special+Elite:regular&v1", :media => "screen, projection"
    = stylesheet_link_tag "print", :media => "print"
    = stylesheet_link_tag "screen", "base", :media => "screen, projection"
    /[if IE]
      = stylesheet_link_tag "ie", :media => "screen, projection"
    = javascript_include_tag "jquery.min.js", "rails.js", "application.js", "http://use.typekit.com/bvq0qsz.js"
    = csrf_meta_tag
    :javascript
      try{Typekit.load();}catch(e){}
  %body
    #header= render :partial => "shared/header"
    #content= render :partial => "shared/content"
    #footer= render :partial => "shared/footer"

app/views/pages/home.html.haml
.prepend-2.span-14.append-2
  %h2 The simplest and prettiest way to manage your death pools
  %p
    Ghoul Pool makes managing your pools dead simple.
    No more spreadsheets.
    No more wasting time trying to organize and stay on top of your picks.
    With our patent-pending, Freebase powered, formally named, Automatic Celebrity Death Tracker or ACDT, you'll never miss an update again.
    What about keeping score?
    Ghoul Pool allows you to structure any scoring scheme, from the basic to the complex; call us eccentric but without the ability to apply obscure ranking algorithms for our pools, it just didn't feel complete.
  %p
    Ghoul Pool is open source; feel free to 
    = link_to "fork it", "https://github.com/chrisbaglieri/ghoulpool"
    for your own needs.
    This particular instance of the application is private.
    While there are no immediate plans to open this to the public, this is the internet, and crazier things have happened.
    

app/views/pools/_form.html.haml
= simple_form_for @pool do |f|
  = f.input :name
  = f.input :picks
  = f.simple_fields_for :rule do |p|
    = p.input :function, :placeholder => "for example ':days_alive * 100'"
  = f.button :submit, :class => "big-button"
  = link_to "Cancel", dashboard_path, :class => "big-button"

app/views/pools/edit.html.haml
%h2 Update Pool
= render :partial => "form"

app/views/pools/new.html.haml
%h2 Create Pool
= render :partial => "form"

app/views/pools/show.html.haml
.span-18.last
  %h2= @pool.name
  %hr
  .span-9
    %h3 Details
    %ul
      %li= "Scoring Function: #{@pool.rule.function}"
      %li= "Pick Count: #{@pool.picks}"
    %h3 Participants
    %ul
      - @pool.users.each do |user|
        %li= user.email
  .span-9.last
    %h3 Actions
    %ul
      %li
        = link_to 'View Your Entries', pool_entries_path(@pool), :class => "small-button"
        = link_to 'Update Pool', edit_pool_path(@pool), :class => "small-button" if can? :update, @pool
        = link_to 'Delete Pool', @pool, :confirm => "Are you sure want to delete this pool?", :method => :delete, :class => "small-button" if can? :destroy, @pool
    %h3 Activity

app/views/shared/_content.html.haml
.container
  .prepend-2.span-20.append-2
    .span-20.inner-container
      .prepend-1.span-18.append-1
        = render :partial => "shared/notifications"
        = yield

app/views/shared/_error_messages.html.haml
- if target.errors.any?
#errorExplanation
  %ul
    - target.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_footer.html.haml
.container

app/views/shared/_header.html.haml
.container
  .prepend-2.span-20.append-2
    %ul#primary-navigation
      = render 'shared/navigation_items'
      = render 'shared/registration_items'
      = render 'shared/login_items'
    %h1 Ghoul Pool

app/views/shared/_login_items.html.haml
- if user_signed_in?
  %li
    = link_to 'Logout', destroy_user_session_path, :class => "small-button"
- else
  %li
    = link_to 'Home', root_path, :class => "small-button"
  %li
    = link_to 'Login', new_user_session_path, :class => "small-button"

app/views/shared/_navigation_items.html.haml
- if user_signed_in?
  %li
    = link_to 'Dashboard', dashboard_path, :class => "small-button"

app/views/shared/_notifications.html.haml
#notifications
  - unless flash[:alert].blank?
    %br
    %p.error= flash[:alert]

app/views/shared/_registration_items.html.haml
- if user_signed_in?
  %li
    = link_to 'Edit registration', edit_user_registration_path, :class => "small-button"